# Generated by Django 3.1.3 on 2020-11-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(),
        ),
    ]
