# Generated by Django 3.1.3 on 2020-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_auto_20201114_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.DateField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
