# Generated by Django 3.1.3 on 2020-11-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_remove_question_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_mark',
            field=models.IntegerField(blank=True),
        ),
    ]
