# Generated by Django 3.1.3 on 2020-11-14 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20201114_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_list',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
