# Generated by Django 3.1.3 on 2020-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_question_list_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='date',
            field=models.DateField(),
        ),
    ]
