# Generated by Django 3.1.3 on 2020-11-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_auto_20201114_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_list',
            name='question_text',
            field=models.TextField(),
        ),
    ]
