# Generated by Django 3.1.3 on 2020-11-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_auto_20201114_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.question_list')),
            ],
        ),
    ]
