# Generated by Django 3.1.3 on 2020-11-14 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0010_answers_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers_list',
            name='question',
        ),
        migrations.AlterField(
            model_name='answers_list',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voting.question_list'),
        ),
    ]
