# Generated by Django 3.1.3 on 2020-11-14 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_auto_20201114_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers_list',
            old_name='price',
            new_name='Оценка',
        ),
    ]
