# Generated by Django 3.1.3 on 2020-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0012_auto_20201114_2023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers_list',
            old_name='name',
            new_name='Вопрос',
        ),
        migrations.RenameField(
            model_name='question_list',
            old_name='question_text',
            new_name='Вопрос',
        ),
        migrations.RenameField(
            model_name='question_list',
            old_name='date',
            new_name='Дата',
        ),
        migrations.RemoveField(
            model_name='question_list',
            name='question_mark',
        ),
        migrations.AddField(
            model_name='answers_list',
            name='Комментарий',
            field=models.TextField(blank=True),
        ),
    ]
