# Generated by Django 3.1.3 on 2020-11-14 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_auto_20201114_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_list',
            old_name='Дата',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='question_list',
            old_name='Вопрос',
            new_name='question_text',
        ),
    ]
