# Generated by Django 3.1.3 on 2020-11-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0014_auto_20201114_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers_list',
            name='Дата',
            field=models.DateField(default='2000-06-12'),
            preserve_default=False,
        ),
    ]
