# Generated by Django 3.1.3 on 2020-11-14 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0015_answers_list_дата'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers_list',
            name='Вопрос',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='voting.question_list'),
        ),
    ]
