# Generated by Django 3.1.3 on 2020-11-14 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0016_auto_20201114_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question_list',
            new_name='Список_вопросов',
        ),
        migrations.RenameModel(
            old_name='Answers_list',
            new_name='Список_ответов',
        ),
    ]
