# Generated by Django 3.1.3 on 2020-11-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0017_auto_20201114_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Список_ПВИ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название_ПВИ', models.CharField(max_length=200)),
                ('Местонахождения', models.CharField(max_length=200)),
            ],
        ),
    ]
