# Generated by Django 3.1.3 on 2020-11-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_список_пви'),
    ]

    operations = [
        migrations.RenameField(
            model_name='список_пви',
            old_name='Местонахождения',
            new_name='Местонахождение_ПВИ',
        ),
    ]
