# Generated by Django 3.1.3 on 2020-11-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0019_auto_20201115_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='список_вопросов',
            name='test',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
