# Generated by Django 3.1.3 on 2020-11-15 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0020_список_вопросов_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='список_вопросов',
            name='test',
        ),
    ]
