# Generated by Django 3.1.3 on 2020-11-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0023_auto_20201115_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Дата_окончания_голосования',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дата', models.DateField()),
            ],
        ),
    ]
