# Generated by Django 3.1.3 on 2020-11-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0024_дата_окончания_голосования'),
    ]

    operations = [
        migrations.AlterField(
            model_name='список_ответов',
            name='Вопрос',
            field=models.TextField(),
        ),
    ]
