# Generated by Django 3.1.3 on 2020-11-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_список_ответов_unique_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Общие_комментарии',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.IntegerField(unique=True)),
                ('Пожелание', models.TextField()),
            ],
        ),
    ]
