# Generated by Django 3.1.3 on 2020-11-20 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0027_общие_комментарии'),
    ]

    operations = [
        migrations.AddField(
            model_name='список_ответов',
            name='ПВИ',
            field=models.TextField(default='ПВИ'),
            preserve_default=False,
        ),
    ]
