# Generated by Django 3.1.3 on 2020-11-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0028_список_ответов_пви'),
    ]

    operations = [
        migrations.AlterField(
            model_name='список_ответов',
            name='unique_key',
            field=models.IntegerField(),
        ),
    ]
