# Generated by Django 3.1.3 on 2020-12-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0036_список_вопросов_num'),
    ]

    operations = [
       
    
    ]
