# Generated by Django 3.1.3 on 2020-12-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0037_список_вопросов_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='дата_окончания_голосования',
            options={'verbose_name': 'Дата_окончания_голосования', 'verbose_name_plural': 'Дата_окончания_голосования'},
        ),
        migrations.AlterModelOptions(
            name='общие_комментарии',
            options={'verbose_name': 'Общие_комментарии', 'verbose_name_plural': 'Общие_комментарии'},
        ),
        migrations.AlterModelOptions(
            name='список_вопросов',
            options={'verbose_name': 'Список_вопросов', 'verbose_name_plural': 'Список_вопросов'},
        ),
        migrations.AlterModelOptions(
            name='список_ответов',
            options={'verbose_name': 'Список_ответов', 'verbose_name_plural': 'Список_ответов'},
        ),
        migrations.AlterModelOptions(
            name='список_пви',
            options={'verbose_name': 'Список_ПВИ', 'verbose_name_plural': 'Список_ПВИ'},
        ),
    ]
