# Generated by Django 3.1.3 on 2020-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0038_auto_20201215_1239'),
    ]

    operations = [
        
    ]
