# Generated by Django 3.1.3 on 2020-12-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0039_список_вопросов_id'),
    ]

    operations = [
      
    ]
