# Generated by Django 3.1.3 on 2020-12-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='name',
            field=models.CharField(default=1, max_length=12),
            preserve_default=False,
        ),
    ]
