# Generated by Django 3.1.3 on 2020-12-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_send_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send',
            name='name',
        ),
        migrations.AddField(
            model_name='send',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send',
            name='review',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
