# Generated by Django 3.1.3 on 2020-12-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201215_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='send',
            options={'verbose_name': 'Отзывы', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
